# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f6da85ffe02dcbcf3f5a6410e043cf0bf87eb240569c12805af1ae5e2c79f1627178880760c650ea6ef8f119babf2a8065a63fb80a2e5ca05195b01901bf6c6

test:
  secret_key_base: d64c6d359044c97bf4010cf31796b7a70b481221457c7d7376915b03d7fdb52ee7c54a01b756f97eeb8538bf7baf0438e27a6831185d5d051d03319ee1b9065d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
